language: ruby
rvm:
  - 2.6.5
services:
  - redis-server
before_script:
  - cp config/settings.yml.travis config/settings.yml
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
sudo: false
cache: bundler
